name: AUTO-RUN

on: [push]
# on:
#   workflow_dispatch:
#   schedule:
#     - cron:  '0,30 * * * *'


jobs:
  run:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 'Start running'
        env:
          DATABASES: ${{ secrets.DATABASES }}
          API_TOKEN: ${{ secrets.API_TOKEN }}
        run: python main.py
